FROM python:3.11-buster

RUN pip install poetry

COPY poetry.lock pyproject.toml ./

ARG POSTGRESQL_URI
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG REDIS_USER_NAME
ARG REDIS_DB
ARG JWT_SECRET_KEY
ARG JWT_ALGORITHM
ARG JWT_EXPIRE_IN_SEC
ARG DOMAIN_EMAIL
ARG EMAIL_PASSWORD
ARG EMAIL_EMAIL
ARG CELERY_BACKEND
ARG CELERY_BROKER


ENV POSTGRESQL_URI=$POSTGRESQL_URI
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PORT=$REDIS_PORT
ENV REDIS_PASSWORD=$REDIS_PASSWORD
ENV REDIS_USER_NAME=$REDIS_USER_NAME
ENV REDIS_DB=$REDIS_DB
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY
ENV JWT_ALGORITHM=$JWT_ALGORITHM
ENV JWT_EXPIRE_IN_SEC=$JWT_EXPIRE_IN_SEC
ENV DOMAIN_EMAIL=$DOMAIN_EMAIL
ENV EMAIL_PASSWORD=$EMAIL_PASSWORD
ENV EMAIL_EMAIL=$EMAIL_EMAIL
ENV CELERY_BACKEND=$CELERY_BACKEND
ENV CELERY_BROKER=$CELERY_BROKER

RUN poetry install

COPY . .
